package mocks

import mock "github.com/stretchr/testify/mock"

// TransfersPublisherMock is an autogenerated mock type for the TransfersPublisher interface.
type TransfersPublisherMock struct {
	mock.Mock
}

// Publish provides a mock function with given fields: operation, transferID
func (_m *TransfersPublisherMock) Publish(operation string, transferID string) error {
	ret := _m.Called(operation, transferID)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(operation, transferID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
