package mocks

import (
	"context"

	models "transfers-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// TransfersRepositoryMock is an autogenerated mock type for the TransfersRepository interface.
type TransfersRepositoryMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, transfer
func (_m *TransfersRepositoryMock) Create(ctx context.Context, transfer models.Transfer) (string, error) {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Transfer) string); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Transfer) error); ok {
		r1 = rf(ctx, transfer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TransfersRepositoryMock) GetByID(ctx context.Context, id string) (models.Transfer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Transfer); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Transfer)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, transfer
func (_m *TransfersRepositoryMock) Update(ctx context.Context, transfer models.Transfer) error {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Transfer) error); ok {
		r0 = rf(ctx, transfer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TransfersRepositoryMock) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *TransfersRepositoryMock) GetAll(ctx context.Context) ([]models.Transfer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) []models.Transfer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySenderID provides a mock function with given fields: ctx, senderID
func (_m *TransfersRepositoryMock) GetBySenderID(ctx context.Context, senderID string) ([]models.Transfer, error) {
	ret := _m.Called(ctx, senderID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySenderID")
	}

	var r0 []models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Transfer); ok {
		r0 = rf(ctx, senderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, senderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByReceiverID provides a mock function with given fields: ctx, receiverID
func (_m *TransfersRepositoryMock) GetByReceiverID(ctx context.Context, receiverID string) ([]models.Transfer, error) {
	ret := _m.Called(ctx, receiverID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReceiverID")
	}

	var r0 []models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Transfer); ok {
		r0 = rf(ctx, receiverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, receiverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
